### ISSUE TITLE
figure feedback

### ISSUE THREAD

**Issue by jovo** [neurodata/ndmg-paper#2]
fig 1) let's label with sub-panels, A, B, C for the 3 levels.  for each level, there should be sub labels (Bi, Bii, Biii, etc.).  the caption must explain each.  look at MGC Fig 1 for an example.  also, where do the atlas and the parcellations come from? i don't see them anywhere in level A? and i don't see the atlas listed in level C?

fig 2) fonts are too small (they should be regular text size.  comment on sorting the nodes differently. the functions for QA must be defined somewhere in text, and referenced in the caption.  consider labeling the 8 panels A, B, C, etc. so they can each be referenced.  consider making panel C monochromatic (black and gray).  consider same for panel 8.

fig 3) font sizes.  consider making line with proportional to # of samples.  consider panel labels. consider using Edge Weight / N (or define normalized explicitly (which is worse). remove 'dd'.

fig 4) font sizes. consider sorting vertices. consider fewer colors and more linestyles. for nnz, use jittered scatterplots per dataset (i saw your comment, i'm not concerned about that)

tab 1) seems like it goes before fig 4? replace MRN with "Discriminabiltiy".  the caption should be fully above the table.  explain what you mean by "total discriminability" in caption. provide link in caption.

fig 5) consider a 10x10 plot averaging over D for each dataset pair, and another showing the variance within each pair.  then we would have both sub-sample and moments from the bigger one that we aren't showing.  consider linking to the bigger one in the caption. compute the p-value for 0.632 different from chance (without errorbars, knowing that it is different is not particularly meaningful). can we compute the score on all the atlases and see which minimizes discriminability?

fig 6) consider moving colorbar to the right side of the std plot.  

(there is no section for abbreviations in nature methods)

**Comment by gkiar** [comment]
Great feedback - thanks! I'm in the process of breaking these into individual issues per-fig and will link them here.

**Comment by gkiar** [comment]
moved to #3 #4 #5 #6 #7 #8 #9. Thanks!
